name: License Checker

on:
  push:
    branches:
    - main
    - "forks/*"
  pull_request:
    branches: 
    - main
    - "v*.*.*-rc"
jobs:
  license-header-check:
    runs-on: ubuntu-latest
    name: license-header-check
    steps:
    - uses: actions/checkout@v3
    - name: Check License Header
      uses: apache/skywalking-eyes/header@df70871af1a8109c9a5b1dc824faaf65246c5236
